CREATE TABLE users(
	userid INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    useraccount VARCHAR(15) NOT NULL,
    username VARCHAR(16) NOT NULL,
    psw VARCHAR(100) NOT NULL,
    avatar MEDIUMTEXT,
    score INT DEFAULT 0
);

CREATE TABLE medicine(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    mname VARCHAR(10) NOT NULL,
    xwgj VARCHAR(20) NOT NULL,
    disc VARCHAR(200) NOT NULL
);